import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useAccount, useReadContract, useWaitForTransactionReceipt, useWriteContract } from "wagmi";
import { formatUnits, parseUnits } from "viem";
import { api } from "../lib/api";
import { clearXAbi, erc20Abi } from "../lib/contracts";
import { ExplorerLink } from "../components/Common";

export function CreateTrade(){
  const {address,chainId}=useAccount(); const {data:cfg}=useQuery({queryKey:["config"],queryFn:api.config});
  const [usd,setUsd]=useState("25"); const [xrp,setXrp]=useState("10"); const [xrpl,setXrpl]=useState(""); const [minutes,setMinutes]=useState(20); const [listed,setListed]=useState(true);
  const {data:decimals=6}=useReadContract({abi:erc20Abi,address:cfg?.usdt0Address??undefined,functionName:"decimals",query:{enabled:!!cfg?.usdt0Address}});
  const amount=usd&&Number(usd)>0?parseUnits(usd,Number(decimals)):0n;
  const {data:balance=0n}=useReadContract({abi:erc20Abi,address:cfg?.usdt0Address??undefined,functionName:"balanceOf",args:address?[address]:undefined,query:{enabled:!!address&&!!cfg?.usdt0Address}});
  const {data:allowance=0n,refetch}=useReadContract({abi:erc20Abi,address:cfg?.usdt0Address??undefined,functionName:"allowance",args:address&&cfg?.clearXContractAddress?[address,cfg.clearXContractAddress]:undefined,query:{enabled:!!address&&!!cfg?.clearXContractAddress&&!!cfg.usdt0Address}});
  const {writeContract,data:hash,isPending,error}=useWriteContract(); const {isLoading:isConfirming,isSuccess}=useWaitForTransactionReceipt({hash});
  const approve=()=>cfg?.usdt0Address&&cfg.clearXContractAddress&&writeContract({abi:erc20Abi,address:cfg.usdt0Address,functionName:"approve",args:[cfg.clearXContractAddress,amount]},{onSuccess:()=>setTimeout(()=>refetch(),3000)});
  const create=()=>cfg?.clearXContractAddress&&writeContract({abi:clearXAbi,address:cfg.clearXContractAddress,functionName:"createTrade",args:[amount,parseUnits(xrp,6),xrpl,BigInt(Math.floor(Date.now()/1000)+minutes*60),listed]});
  const ready=!!address&&chainId===114&&!!cfg?.configured&&amount>0n&&Number(xrp)>0&&xrpl.startsWith("r")&&balance>=amount;
  return <><section className="hero"><span className="eyebrow">PAYMENT-VERSUS-PAYMENT ON FLARE</span><h1>Native XRP settlement, without sending first.</h1><p>Lock a Flare asset, pay native XRP, and let FDC prove the payment before settlement.</p><div className="proof-chips"><span>XRPL Testnet</span><span>Flare Coston2</span><span>Verified by FDC</span></div></section><section className="console"><div className="tabs"><b>Create trade</b><a href="/open">Open trade</a></div>{!cfg?.configured&&<div className="notice warning">Deployment configuration is pending. Add the verified USD₮0 and ClearX contract addresses after Coston2 deployment.</div>}<div className="amount-grid"><label className="amount-panel"><span>YOU LOCK</span><div><input value={usd} onChange={e=>setUsd(e.target.value)} inputMode="decimal"/><strong>USD₮0<small>Flare Coston2</small></strong></div><small>Balance {formatUnits(balance,Number(decimals))}</small></label><div className="direction">→</div><label className="amount-panel"><span>YOU RECEIVE</span><div><input value={xrp} onChange={e=>setXrp(e.target.value)} inputMode="decimal"/><strong>XRP<small>XRP Ledger</small></strong></div><small>Rate agreed directly with your counterparty.</small></label></div><div className="form-grid"><label>Your XRP receiving address<input value={xrpl} onChange={e=>setXrpl(e.target.value.trim())} placeholder="rXXXXXXXXXXXXXXXXXXXXXXXXXXXX"/><small>Native XRP is sent directly here. ClearX never holds it.</small></label><label>Settlement window<select value={minutes} onChange={e=>setMinutes(Number(e.target.value))}><option value={15}>15 minutes</option><option value={20}>20 minutes</option><option value={30}>30 minutes</option><option value={60}>1 hour</option></select><small>FDC normally takes about 90-180 seconds.</small></label></div><label className="check"><input type="checkbox" checked={listed} onChange={e=>setListed(e.target.checked)}/> List this funded settlement publicly</label>{error&&<div className="notice error">{error.message}</div>}<div className="action-row">{allowance<amount?<button className="primary" disabled={!ready||isPending||isConfirming} onClick={approve}>{isPending?"Confirm in wallet...":isConfirming?"Approving USD₮0...":`Approve ${usd||"0"} USD₮0`}</button>:<button className="primary" disabled={!ready||isPending||isConfirming} onClick={create}>{isPending?"Confirm in wallet...":isConfirming?"Locking USD₮0...":"Lock & create settlement"}</button>}</div>{hash&&cfg&&<ExplorerLink href={`${cfg.explorerUrl}/tx/${hash}`}>{isSuccess?"Transaction confirmed":"View pending transaction"}</ExplorerLink>}</section><SettlementRail/><Trust/></>;
}
function SettlementRail(){return <section className="rail"><div><b>XRP Ledger</b><span>Native XRP payment</span></div><i>→</i><div className="fdc"><b>Flare Data Connector</b><span>Payment proof</span></div><i>→</i><div><b>Flare Coston2</b><span>USD₮0 release</span></div></section>}
function Trust(){return <section className="trust"><article><h3>No send-first risk</h3><p>The Flare asset is funded before native XRP moves.</p></article><article><h3>Native XRP stays native</h3><p>XRP moves directly between XRP Ledger accounts.</p></article><article><h3>Flare verifies reality</h3><p>USD₮0 moves only after the FDC proof passes onchain.</p></article></section>}

