import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { useAccount, useWriteContract } from "wagmi";
import { formatUnits } from "viem";
import { api } from "../lib/api";
import { clearXAbi } from "../lib/contracts";
import type { Job } from "../types";
import { Empty, ExplorerLink, Loading, StatusPill } from "../components/Common";
import { canonicalXrplTxHash, copy, short } from "../lib/format";
const statusNames=["NONE","OPEN","RESERVED","SETTLED","CANCELLED"];
export function TradeDetail(){const {id=""}=useParams();const {address}=useAccount();const {data:cfg}=useQuery({queryKey:["config"],queryFn:api.config});const q=useQuery({queryKey:["trade",id],queryFn:()=>api.trade(id),refetchInterval:8000});const {writeContract,isPending,error}=useWriteContract();const [xrpl,setXrpl]=useState("");const [hash,setHash]=useState("");const [job,setJob]=useState<Job>();
useEffect(()=>{if(!job||["SETTLED","FAILED"].includes(job.stage))return;const timer=setInterval(()=>api.job(job.id).then(setJob).catch(()=>{}),5000);return()=>clearInterval(timer)},[job]);
if(q.isLoading)return <section className="page"><Loading/></section>;if(q.error||!q.data)return <section className="page"><Empty title="Settlement not found" body="Check the settlement link and try again." action={<Link to="/open">Browse open settlements</Link>}/></section>;const t=q.data;const maker=address?.toLowerCase()===t.maker.toLowerCase();const taker=address?.toLowerCase()===t.taker.toLowerCase();const canReclaim=Date.now()/1000>t.expiry+900;const write=(fn:any,args:any[])=>cfg?.clearXContractAddress&&writeContract({abi:clearXAbi,address:cfg.clearXContractAddress,functionName:fn,args} as any,{onSuccess:()=>setTimeout(()=>q.refetch(),4000)});const start=async()=>setJob(await api.startJob(t.id,hash));
return <section className="page narrow"><div className="trade-header"><div><small>Settlement #{t.id}</small><h1>{statusNames[t.status]}</h1></div><StatusPill tone={t.status===3?"success":t.status===2?"warning":"neutral"}>{statusNames[t.status]}</StatusPill></div><div className="locked-banner"><b>{formatUnits(BigInt(t.usdt0Amount),6)} USD₮0 locked on Coston2 ✓</b><span>The asset can move only after an accepted FDC payment proof.</span>{cfg&&<ExplorerLink href={`${cfg.explorerUrl}/address/${cfg.clearXContractAddress}`}>View contract</ExplorerLink>}</div><div className="settlement-summary"><div><small>{maker?"YOU LOCKED":"YOU RECEIVE"}</small><strong>{formatUnits(BigInt(t.usdt0Amount),6)} USD₮0</strong><span>Flare Coston2</span></div><i>↔</i><div><small>{maker?"YOU RECEIVE":"YOU PAY"}</small><strong>{formatUnits(BigInt(t.xrpAmountDrops),6)} XRP</strong><span>Native XRP Ledger</span></div></div><div className="facts"><div><small>Maker</small><b>{short(t.maker)}</b></div><div><small>Reference</small><button onClick={()=>copy(t.paymentReference)}>{short(t.paymentReference)} Copy</button></div><div><small>Expires</small><b>{new Date(t.expiry*1000).toLocaleString()}</b></div><div><small>Listing</small><b>{t.isPublic?"Public":"Private"}</b></div></div>
{t.status===1&&!maker&&<div className="flow-card"><h2>Reserve settlement</h2><p>Enter the exact XRP Ledger address you will pay from.</p><label>You will send XRP from<input value={xrpl} onChange={e=>setXrpl(e.target.value.trim())} placeholder="rTAKER..."/></label><button className="primary" disabled={!address||!xrpl.startsWith("r")||isPending} onClick={()=>write("acceptTrade",[BigInt(t.id),xrpl])}>Reserve settlement</button></div>}
{t.status===1&&maker&&<div className="button-row"><button onClick={()=>copy(location.href)}>Copy settlement link</button><button onClick={()=>write("setPublicListing",[BigInt(t.id),!t.isPublic])}>{t.isPublic?"Unlist":"List publicly"}</button><button className="danger" onClick={()=>write("cancelOpenTrade",[BigInt(t.id)])}>Cancel settlement</button></div>}
{t.status===2&&taker&&<div className="flow-card payment"><div className="payment-title"><div><small>SEND EXACTLY</small><h2>{formatUnits(BigInt(t.xrpAmountDrops),6)} XRP</h2></div><StatusPill tone="warning">AWAITING XRP</StatusPill></div><CopyField label="TO" value={t.makerXrplAddress}/><CopyField label="MEMO - REQUIRED" value={t.paymentReference.slice(2).toUpperCase()}/><div className="notice warning"><b>The memo is required.</b> Send from {t.takerXrplAddress} before the deadline.</div><label>Already sent XRP?<input value={hash} onChange={e=>setHash(e.target.value.trim())} placeholder="Paste the 64-character XRPL transaction hash"/></label><button className="primary" disabled={!/^[A-Fa-f0-9]{64}$/.test(hash)||!!job} onClick={start}>Verify & settle</button>{job&&<Progress job={job} cfg={cfg}/>}</div>}
{t.status===2&&maker&&<div className="flow-card"><h2>Counterparty reserved</h2><p>Expected XRP source: <b>{t.takerXrplAddress}</b></p><p>No maker action is required while the payment and FDC proof complete.</p>{canReclaim&&<button className="danger" onClick={()=>write("reclaimExpiredTrade",[BigInt(t.id)])}>Reclaim locked USD₮0</button>}</div>}
{t.status===3&&<Success trade={t} cfg={cfg}/>} {error&&<div className="notice error">{error.message}</div>}</section>}
function CopyField({label,value}:{label:string;value:string}){return <div className="copy-field"><small>{label}</small><code>{value}</code><button onClick={()=>copy(value)}>Copy</button></div>}
function Progress({job,cfg}:{job:Job;cfg:any}){const stages=["PREFLIGHT","FDC_SUBMITTED","FDC_WAITING","PROOF_READY","SETTLING","SETTLED"];const current=stages.indexOf(job.stage);return <div className="progress"><h3>Verifying cross-chain payment</h3>{["XRP transaction found","FDC request submitted","Waiting for FDC consensus","Payment proof verified","Release USD₮0"].map((name,i)=><div className={i<current?"done":i===current?"active":""} key={name}><i>{i<current?"✓":i+1}</i><span><b>{name}</b>{i===2&&job.votingRoundId&&<small>Voting round #{job.votingRoundId}</small>}{i===1&&job.fdcRequestTxHash&&<ExplorerLink href={`${cfg.explorerUrl}/tx/${job.fdcRequestTxHash}`}>Request transaction</ExplorerLink>}</span></div>)}{job.stage==="FAILED"&&<div className="notice error">{job.errorMessage}</div>}</div>}
function Success({trade,cfg}:{trade:any;cfg:any}){const xrplHash=canonicalXrplTxHash(trade.settlementXrplTx);return <div className="success-panel"><div className="success-check">✓</div><div><StatusPill tone="success">COMPLETED</StatusPill><h2>Settlement complete</h2><p>The native XRP payment was proven and the locked USD₮0 was released.</p></div><div className="proof-grid"><article><small>XRP LEDGER</small><b>{formatUnits(BigInt(trade.xrpAmountDrops),6)} XRP</b>{cfg&&<ExplorerLink href={`${cfg.xrplExplorerTxBaseUrl}${xrplHash}`}>XRPL transaction</ExplorerLink>}</article><article><small>FLARE DATA CONNECTOR</small><b>Payment proven</b><span>Verified onchain</span></article><article><small>FLARE COSTON2</small><b>{formatUnits(BigInt(trade.usdt0Amount),6)} USD₮0</b><span>Released to taker</span></article></div><Link className="primary link-button" to="/">Create another settlement</Link></div>}
