import { useEffect, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { useAccount, useWriteContract } from "wagmi";
import { formatUnits } from "viem";
import { api } from "../lib/api";
import { clearXAbi } from "../lib/contracts";
import { canonicalXrplTxHash, short } from "../lib/format";
import { useMarketPrice, usd } from "../lib/market";
import { buildGemWalletPayment, xrplPaymentGuard } from "../lib/xrpl-wallet";
import { useXrplWallet } from "../contexts/XrplWalletContext";
import type { Job } from "../types";
import { CopyButton, Empty, ExplorerLink, Loading, Metric, StatusPill } from "../components/Common";
import { ArrowRight, ShieldIcon, TokenIcon, WalletIcon } from "../components/Icons";

const statusNames = ["NONE", "OPEN", "RESERVED", "SETTLED", "CANCELLED"];
export function TradeDetail() {
  const { id = "" } = useParams(); const { address } = useAccount(); const gem = useXrplWallet(); const market = useMarketPrice();
  const { data: cfg } = useQuery({ queryKey: ["config"], queryFn: api.config });
  const q = useQuery({ queryKey: ["trade", id], queryFn: () => api.trade(id), refetchInterval: 6000 });
  const { writeContract, isPending, error } = useWriteContract(); const [xrpl, setXrpl] = useState(""); const [hash, setHash] = useState(""); const [job, setJob] = useState<Job>(); const [walletError, setWalletError] = useState(""); const [signing, setSigning] = useState(false); const [advanced, setAdvanced] = useState(false);
  const paymentStarted = useRef(false);
  useEffect(() => { if (gem.connected && gem.network === "Testnet" && gem.address && !xrpl) setXrpl(gem.address); }, [gem.connected, gem.network, gem.address, xrpl]);
  useEffect(() => { if (!job || ["SETTLED", "FAILED"].includes(job.stage)) return; const timer = setInterval(() => api.job(job.id).then(next => { setJob(next); if (next.stage === "SETTLED") void q.refetch(); }).catch(() => {}), 4000); return () => clearInterval(timer); }, [job, q]);
  if (q.isLoading) return <section className="page"><Loading /></section>;
  if (q.error || !q.data) return <section className="page"><Empty title="Settlement not found" body="Check the settlement link and try again." action={<Link className="primary" to="/open">Browse markets</Link>} /></section>;
  const t = q.data; const maker = address?.toLowerCase() === t.maker.toLowerCase(); const taker = address?.toLowerCase() === t.taker.toLowerCase(); const expired = Date.now() / 1000 > t.expiry; const canReclaim = Date.now() / 1000 > t.expiry + 900;
  const write = (fn: string, args: unknown[]) => cfg?.clearXContractAddress && writeContract({ abi: clearXAbi, address: cfg.clearXContractAddress, functionName: fn, args } as never, { onSuccess: () => setTimeout(() => void q.refetch(), 4000) });
  const start = async (txHash = hash) => { const normalized = canonicalXrplTxHash(txHash); setHash(normalized); setJob(await api.startJob(t.id, normalized)); };
  const walletState = xrplPaymentGuard({ installed: gem.installed, connected: gem.connected, network: gem.network, address: gem.address, reservedAddress: t.takerXrplAddress, expired });
  const payWithGem = async () => { if (paymentStarted.current) return; paymentStarted.current = true; setWalletError(""); setSigning(true); try { buildGemWalletPayment(gem.address!, t.makerXrplAddress, t.xrpAmountDrops, t.paymentReference); const txHash = await gem.submitPayment(t.makerXrplAddress, t.xrpAmountDrops, t.paymentReference); await start(txHash); } catch (e) { paymentStarted.current = false; setWalletError(e instanceof Error ? e.message : "GemWallet payment failed"); } finally { setSigning(false); } };
  const usdt = Number(formatUnits(BigInt(t.usdt0Amount), 6)); const xrp = Number(formatUnits(BigInt(t.xrpAmountDrops), 6)); const marketXrp = xrp * (market.data?.priceUsd ?? 0); const implied = xrp ? usdt / xrp : 0; const premium = market.data?.priceUsd ? ((implied / market.data.priceUsd) - 1) * 100 : 0;
  return <section className="page settlement-page">
    <div className="trade-header"><div><span className="section-kicker">SETTLEMENT #{t.id}</span><h1>{statusNames[t.status]}</h1><p>Onchain payment-versus-payment workspace</p></div><div className="header-status"><StatusPill tone={t.status === 3 ? "success" : t.status === 2 ? "warning" : t.status === 4 ? "danger" : "neutral"}>{statusNames[t.status]}</StatusPill>{cfg && <ExplorerLink href={`${cfg.explorerUrl}/address/${cfg.clearXContractAddress}`}>Contract</ExplorerLink>}</div></div>
    <div className="settlement-layout"><div className="settlement-main">
      <div className="locked-banner"><ShieldIcon /><div><b>{usdt} USD₮0 secured in ClearX</b><span>{t.status === 3 ? "Released after verified XRP payment" : "Escrow can move only after an accepted FDC proof"}</span></div><StatusPill tone={t.status === 3 ? "success" : "neutral"}>{t.status === 3 ? "RELEASED" : "FUNDED"}</StatusPill></div>
      <div className="settlement-summary premium"><AssetSummary label={maker ? "YOU LOCKED" : "YOU RECEIVE"} token="usdt0" amount={`${usdt} USD₮0`} fiat={usd(usdt)} network="Flare Coston2" /><div className="swap-direction"><ArrowRight /></div><AssetSummary label={maker ? "YOU RECEIVE" : "YOU PAY"} token="xrp" amount={`${xrp} XRP`} fiat={market.data ? usd(marketXrp) : "—"} network="XRP Ledger Testnet" /></div>
      <div className="facts"><Metric label="MAKER" value={short(t.maker)} detail={t.makerXrplAddress ? short(t.makerXrplAddress) : "XRPL pending"} /><Metric label="REFERENCE" value={short(t.paymentReference)} detail={<CopyButton value={t.paymentReference} label="Copy" />} /><Metric label="DEADLINE" value={new Date(t.expiry * 1000).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })} detail={expired ? "Expired" : new Date(t.expiry * 1000).toLocaleDateString()} /><Metric label="RATE" value={`${usd(implied)}/XRP`} detail={market.data ? `${premium >= 0 ? "+" : ""}${premium.toFixed(1)}% vs spot` : "Market loading"} /></div>
      {t.status === 1 && !maker && <ReserveCard xrpl={xrpl} setXrpl={setXrpl} gem={gem} isPending={isPending} onReserve={() => write("acceptTrade", [BigInt(t.id), xrpl])} />}
      {t.status === 1 && maker && <div className="flow-card"><div className="card-heading"><div><span className="section-kicker">MAKER CONTROLS</span><h2>Settlement is open</h2></div><StatusPill tone="success">FUNDED</StatusPill></div><p>Share this settlement or let a counterparty discover it in the public market.</p><div className="button-row"><CopyButton value={location.href} label="Copy link" /><button className="secondary" onClick={() => write("setPublicListing", [BigInt(t.id), !t.isPublic])}>{t.isPublic ? "Unlist" : "List publicly"}</button><button className="danger" onClick={() => write("cancelOpenTrade", [BigInt(t.id)])}>Cancel & reclaim</button></div></div>}
      {t.status === 2 && taker && <PaymentCard trade={t} gem={gem} walletState={walletState} signing={signing} walletError={walletError} hash={hash} setHash={setHash} advanced={advanced} setAdvanced={setAdvanced} job={job} cfg={cfg} onConnect={() => void gem.connect()} onPay={() => void payWithGem()} onManual={() => void start()} />}
      {t.status === 2 && maker && <div className="flow-card waiting-card"><TokenIcon token="xrp" size={48} /><div><span className="section-kicker">COUNTERPARTY RESERVED</span><h2>Waiting for native XRP</h2><p>Expected source: <b>{t.takerXrplAddress}</b>. FDC settlement requires no maker action.</p></div>{canReclaim && <button className="danger" onClick={() => write("reclaimExpiredTrade", [BigInt(t.id)])}>Reclaim escrow</button>}</div>}
      {t.status === 3 && <Success trade={t} cfg={cfg} />}{(error || walletError) && <div className="notice error">{error?.message || walletError}</div>}
    </div><aside className="settlement-aside"><div className="aside-card"><span className="section-kicker">SETTLEMENT ROUTE</span><h3>Two networks, one condition</h3><RouteStep icon="flare" title="USD₮0 funded" detail="Coston2 escrow" done={t.status >= 1} /><RouteStep icon="xrp" title="XRP payment" detail="Direct wallet transfer" done={t.status >= 3} active={t.status === 2} /><RouteStep icon="fdc" title="FDC proof" detail="Decentralized consensus" done={t.status >= 3} active={!!job && t.status === 2} /><RouteStep icon="usdt0" title="Asset release" detail="To reserved taker" done={t.status === 3} /></div><div className="aside-card market-card"><small>MARKET REFERENCE</small><b>1 XRP = {market.data ? usd(market.data.priceUsd) : "—"}</b><span>{market.data?.stale ? "Cached price" : "Coinbase spot · live"}</span><p>Reference only. ClearX executes the bilateral amounts above.</p></div></aside></div>
  </section>;
}

function AssetSummary({ label, token, amount, fiat, network }: { label: string; token: "xrp" | "usdt0"; amount: string; fiat: string; network: string }) { return <div className="asset-summary"><small>{label}</small><div><TokenIcon token={token} size={46} /><span><strong>{amount}</strong><em>{fiat} · {network}</em></span></div></div>; }
function ReserveCard({ xrpl, setXrpl, gem, isPending, onReserve }: { xrpl: string; setXrpl: (v: string) => void; gem: ReturnType<typeof useXrplWallet>; isPending: boolean; onReserve: () => void }) { return <div className="flow-card"><div className="card-heading"><div><span className="section-kicker">TAKER STEP 1</span><h2>Reserve this funded settlement</h2></div><TokenIcon token="gem" size={42} /></div><p>Bind the exact XRPL account that will send the payment.</p><label>XRPL source address<div className="input-with-action"><input value={xrpl} onChange={e => setXrpl(e.target.value.trim())} placeholder="rTAKER…" />{gem.connected ? <button type="button" onClick={() => gem.address && setXrpl(gem.address)}>Use connected</button> : <button type="button" onClick={() => void gem.connect()}>Connect GemWallet</button>}</div></label>{gem.connected && <div className={`wallet-proof ${gem.network === "Testnet" ? "good" : "bad"}`}><WalletIcon /><span>{short(gem.address!)}<small>GemWallet · {gem.network}</small></span></div>}<button className="primary action-main sticky-action" disabled={!xrpl.startsWith("r") || isPending || (gem.connected && gem.network !== "Testnet")} onClick={onReserve}>{isPending ? "Confirm in MetaMask…" : "Reserve settlement"}</button></div>; }
function PaymentCard({ trade, gem, walletState, signing, walletError, hash, setHash, advanced, setAdvanced, job, cfg, onConnect, onPay, onManual }: any) { const message: Record<string, string> = { WALLET_REQUIRED: "Connect GemWallet to pay directly from ClearX.", WRONG_NETWORK: `Switch GemWallet from ${gem.network ?? "its current network"} to XRPL Testnet.`, ADDRESS_MISMATCH: `Connected ${short(gem.address ?? "")} does not match reserved ${short(trade.takerXrplAddress)}.`, EXPIRED: "The XRP payment deadline has passed." }; return <div className="flow-card payment"><div className="card-heading"><div><span className="section-kicker">TAKER STEP 2</span><h2>Pay native XRP</h2></div><StatusPill tone="warning">AWAITING PAYMENT</StatusPill></div><div className="payment-amount"><TokenIcon token="xrp" size={52} /><div><small>SEND EXACTLY</small><strong>{formatUnits(BigInt(trade.xrpAmountDrops), 6)} XRP</strong></div></div><Instruction label="Destination" value={trade.makerXrplAddress} /><Instruction label="Required 32-byte memo" value={trade.paymentReference.slice(2).toUpperCase()} />
  <div className={`gem-panel ${walletState === "READY_TO_PAY" ? "ready" : ""}`}><div><TokenIcon token="gem" size={42} /><span><b>{gem.connected ? short(gem.address!) : "GemWallet"}</b><small>{gem.connected ? `${gem.network} · ${walletState === "READY_TO_PAY" ? "Ready to sign" : "Action required"}` : "External XRPL signer"}</small></span></div>{walletState !== "READY_TO_PAY" && <p>{message[walletState]}</p>}{!gem.connected ? <button className="primary" onClick={onConnect}>Connect GemWallet</button> : <button className="primary action-main sticky-action" disabled={walletState !== "READY_TO_PAY" || signing || !!job} onClick={onPay}>{signing ? "Confirm in GemWallet…" : `Pay ${formatUnits(BigInt(trade.xrpAmountDrops), 6)} XRP with GemWallet`}</button>}</div>
  {walletError && <div className="notice error">{walletError}</div>}{job && <Progress job={job} cfg={cfg} />}
  {!job && <div className="advanced"><button className="advanced-toggle" onClick={() => setAdvanced(!advanced)}>{advanced ? "Hide manual fallback" : "Paid externally? Use transaction hash"}</button>{advanced && <div className="manual-payment"><label>XRPL transaction hash<input value={hash} onChange={e => setHash(e.target.value.trim())} placeholder="64-character validated hash" /></label><button className="secondary" disabled={!/^[A-Fa-f0-9]{64}$/.test(hash)} onClick={onManual}>Verify external payment</button></div>}</div>}</div>; }
function Instruction({ label, value }: { label: string; value: string }) { return <div className="instruction"><small>{label}</small><code>{value}</code><CopyButton value={value} /></div>; }
function Progress({ job, cfg }: { job: Job; cfg: any }) { const stages = ["PREFLIGHT", "FDC_SUBMITTED", "FDC_WAITING", "PROOF_READY", "SETTLING", "SETTLED"]; const current = stages.indexOf(job.stage); return <div className="progress"><div className="progress-head"><span><i className="pulse" />LIVE SETTLEMENT</span><b>{job.stage.replaceAll("_", " ")}</b></div>{["XRP transaction validated", "FDC request submitted", "Consensus finalized", "Merkle proof retrieved", "USD₮0 released"].map((name, i) => <div className={i < current ? "done" : i === current ? "active" : ""} key={name}><i>{i < current ? "✓" : i + 1}</i><span><b>{name}</b>{i === 2 && job.votingRoundId && <small>Voting round #{job.votingRoundId}</small>}{i === 1 && job.fdcRequestTxHash && <ExplorerLink href={`${cfg.explorerUrl}/tx/${job.fdcRequestTxHash}`}>Request transaction</ExplorerLink>}</span></div>)}{job.stage === "FAILED" && <div className="notice error">{job.errorMessage}</div>}</div>; }
function RouteStep({ icon, title, detail, done, active }: { icon: "xrp" | "usdt0" | "flare" | "fdc"; title: string; detail: string; done?: boolean; active?: boolean }) { return <div className={`route-step ${done ? "done" : ""} ${active ? "active" : ""}`}><TokenIcon token={icon} size={32} /><span><b>{title}</b><small>{detail}</small></span><i>{done ? "✓" : active ? "•••" : "○"}</i></div>; }
function Success({ trade, cfg }: { trade: any; cfg: any }) { const xrplHash = canonicalXrplTxHash(trade.settlementXrplTx); return <div className="success-panel"><div className="success-check">✓</div><div><StatusPill tone="success">COMPLETED</StatusPill><h2>Settlement complete</h2><p>The native XRP payment was proven by FDC and the locked USD₮0 was released.</p></div><div className="proof-grid"><article><TokenIcon token="xrp" /><small>XRP LEDGER</small><b>{formatUnits(BigInt(trade.xrpAmountDrops), 6)} XRP</b>{cfg && <ExplorerLink href={`${cfg.xrplExplorerTxBaseUrl}${xrplHash}`}>XRPL transaction</ExplorerLink>}</article><article><TokenIcon token="fdc" /><small>FLARE DATA CONNECTOR</small><b>Payment proven</b><span>Verified onchain</span></article><article><TokenIcon token="usdt0" /><small>FLARE COSTON2</small><b>{formatUnits(BigInt(trade.usdt0Amount), 6)} USD₮0</b><span>Released to taker</span></article></div><Link className="primary link-button" to="/">Create another settlement <ArrowRight /></Link></div>; }
